version: '3.8'

services:
  app-dev:
    container_name: mississippi-app-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - ${APP_PORT:-4444}:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev --name init && npm run start:dev"
    profiles:
      - dev

  db:
    image: postgres:17-alpine
    container_name: mississippi-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT:-5434}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
